apiVersion: v1
kind: Service
metadata:

  labels:
    kubernetes.courselabs.co: hackathon
    app: widgetario
spec:
  ports:

      targetPort: http
  selector:  
    app: widgetario
    component: web

